# Generated by Django 4.2.6 on 2023-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='id',
        ),
        migrations.AlterField(
            model_name='new',
            name='id_user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
