# Generated by Django 4.2.6 on 2023-10-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_new_id_alter_new_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='comp',
            new_name='liga',
        ),
        migrations.AddField(
            model_name='new',
            name='photo',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
